### ISSUE TITLE
Write migration guide & manually test migration for FF v1.1->v1.2

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/firefly#1146]

**Comment by Rabax55** [comment]
Pls include the following Discord-thread with your tests, thx:
https://discord.com/channels/905194001349627914/928377875827154984/threads/1062145402834526228

**Comment by nguyer** [comment]
Hi @Rabax55, sorry it doesn't look like that link is working anymore. Do you mind posting here which tests you were hoping to have run? Thanks!

**Comment by Rabax55** [comment]
It's with the FF-Upgrade, and on Besu-Networks only:

From the Discord-Thread:

"...just upgraded my FF-Version from 1.1.1 to 1.1.2:

jms@LAP-10:~$ ff upgrade proc_10
jms@LAP-10:~$ upgrading stack  'proc_10'... done
Your stack has been upgraded.

After starting the upgraded stack, the stacks core-nodes fail to start. The Docker-Image logs state:
2023-01-09 23:51:01 FF10412: Bad network version: %!!(MISSING)s(<nil>) "

Easy to reproduce (w/ versions 1.1.1 and 1.1.2 (a real upgrade), or just use a freshly created Besu-stack/Version 1.1.2 (nothing to upgrade). From the Discord-Thread:
"-> The problem is with 1. the upgrade and 2. on besu networks only 
-> It occurs on all versions 1.1.1 and 1.1.2
-> It occurs even if there is nothing to upgrade
-> Easy to reproduce: fire up any Besu-stack (with whatever version), directly start the upgrade-cmd, wait some seconds, check the result..."

Regards, Joerg

**Comment by nguyer** [comment]
Thanks for the details! That should be tracked as a separate issue/bug on https://github.com/hyperledger/firefly-cli itself. This issue is for testing that FireFly itself can upgrade cleanly from one version to the next, regardless of automation with the CLI.
