### ISSUE TITLE
Late joiners to a multiparty network fail to process previous definitions

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#1221]
Say I build a multiparty network with N members, and they each secure their identity, and then later broadcast some definitions (token pools, interfaces, etc).

Then member N+1 joins the network and begins processing all messages to catch up. Because this member will be processing everything as quickly as possible, and because this processing happens on parallel threads, and because identities and other definitions are on separate topics... it's quite likely that some definition messages may be parsed before the identities of all prior nodes have been parsed and confirmed.

When this happens, the new node will simply reject those definitions:

https://github.com/hyperledger/firefly/blob/35319a22f7a468381105e7f79a4363fe5778879a/internal/events/aggregator.go#L437

We need a better way to handle the "unknown author" situation - possibly some new "parked" state for these definitions, so that we can go back and process them in order if the author becomes resolved.

**Comment by awrichar** [comment]
My first pass on the simplest solution...
1. Instead of rejecting at this moment, put the message in a new state (maybe "Unidentified" or possibly "Untrusted") which is similar to Pending.
2. Whenever a new identity is confirmed, check for messages from that DID in this new state, and queue rewinds for each of those messages.

This adds a new database query to (2), but that should be an infrequently used flow anyway.

This seems too simple though, so I feel like I'm probably missing something.

**Comment by peterbroadhurst** [comment]
I had a concern concern if an org gets confirmed because of an IPFS download, and we're somewhere in the pins table processing messages, we might process the very next message from that org _forwards_ from that point.

I'm wondering if it's possible for that to mean we process (within topic constraints  admittedly) broadcasts for that org in a rather arbitrary order - from wherever we were at when we confirmed.

e.g. that (2) in your point above, is actually required.

However, now I read this back again - I realized we can only possibly be processing the pins sequentially at the point we rewind back (because of the completed IPFS download) to process the org successfully.

So that means it's perfectly safe to just work _forwards_ from there.

So if I understand this thinking correctly, just leaving the pins undispatched/pending would fix this issue.

**Comment by awrichar** [comment]
Ah right, completed downloads just trigger a rewind. I think you're right that the pins would get picked up as long as they're still undispatched.

I was also trying to work out if there's any way the identity pin could get ordered _after_ the definition pin, which would add a weird edge case... but I don't think it should be possible for the author to dispatch them out of order.
