### ISSUE TITLE
Retried operations pollute the cache with incorrect values

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#1310]
Given operation A, which failed.
I retried operation A, which created operation B.
Now, when performing a "get one" to get operation A, it actually returns the details of operation B.
When performing a "get many", the details of operation A can be retrieved correctly.

Somehow it seems like the cache became polluted (since the "get one" API goes to the cache). I haven't pinpointed the exact path, but it may be somewhere around this area:
https://github.com/hyperledger/firefly/blob/4df24f30508b046fe57def1d386d2fb73a5d1979/internal/operations/manager.go#L214

**Comment by dwertent** [comment]
@awrichar I believe the issue occurs because [this function](https://github.com/hyperledger/firefly/blob/4df24f30508b046fe57def1d386d2fb73a5d1979/internal/operations/manager.go#L290) returns a reference to the cached object. Later, in [this section](https://github.com/hyperledger/firefly/blob/4df24f30508b046fe57def1d386d2fb73a5d1979/internal/operations/manager.go#L201), the object's ID is overwritten with a new one. This causes a mismatch where the cache key still uses the old ID, but the cached object now contains the new ID.

To resolve this, we could add a deep copy either [here](https://github.com/hyperledger/firefly/blob/4df24f30508b046fe57def1d386d2fb73a5d1979/internal/operations/manager.go#L290) or [here](https://github.com/hyperledger/firefly/blob/4df24f30508b046fe57def1d386d2fb73a5d1979/internal/operations/manager.go#L195).
