### ISSUE TITLE
`FF23021: EVM reverted` errors during invoke with `idempotencyKey` leaves ops in `Initializing` status

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#1435]
In PR #1406 we closed a problem scenario, where we might incorrectly return a `409` after a failure that did not actually propagate an `operation` all the way down to the underlying connector.

The change was in-line with the original architecture of the idempotency keys. Without it, transactions could end up in a "lost" state in edge cases such as a connector forceful restart or a DB unavailability behind the connector - where the application could not re-submit the transaction because it was marked at known (hence `409 Conflict`), but the connector had not successfully persisted the transaction to its store.

However, this safety change introduces a change in behavior that is also problematic for applications.

In the case of a `FF23021: EVM reverted` error during gas estimation, which occurs as par of FFTM based connectors (like EVMConnect) _accepting the operation_, the operation will never exit `Initializing` status.

Thus the application will get a `500` error permanently on every subsequent retry. They will never reach the point of a `409`, and the operation will never reach the point of a `Failed` status.

For reference, the architecture for idempotent TX submission across all connectors is described here:
https://hyperledger.github.io/firefly/head/reference/idempotency.html

**Comment by peterbroadhurst** [comment]
### Strawman

I believe it is a more obvious and explainable behavior, if these situations were to instead immediately transition an operation to `Failed` status - re-instating the behavior before #1406.

However, that _the connector_ must be responsible for reporting that the nature of the failure to accept the transaction is a **Reject** of the transaction, rather than a temporary condition.

That will be a complex per-connector decision.
In this specific case in EVMConnect:
- The `eth_estimateGas` operation returned an error from the blockchain node JSON/RPC interface
- The "Revert reason" was successfully extracted from the response, so we are confident the issue is not transient

![Uploading image.png…]()

**Comment by nguyer** [comment]
I like the general idea of the "Proposed" solution. One question would be whether it should return `500` or `400` after it updates the status to `Failed`, indicating that it is not a retryable error.

**Comment by peterbroadhurst** [comment]
I like the idea of the spelling of "Reject" being returning HTTP Status code `400` 👍

**Comment by peterbroadhurst** [comment]
Actually, I wonder if there is a tweak here @nguyer - to your great point. That we should propagate the `400` all the way back to the application, and instead of leaving the transaction in `Initializing` status, we should remove the record before returning the `400`. I'll do a tweaked sequence diagram for this, for us to consider.

**Comment by peterbroadhurst** [comment]
### Counter proposal

![image](https://github.com/hyperledger/firefly/assets/6660217/37f5eacf-954a-4928-9d62-04d4ecb0e559)

[sequence diagram source](https://sequencediagram.org/index.html#initialData=C4S2BsFMAIBUA1oGcCuAjAtiJSQHsA7aYPaAUQDUBZAYUIMgGNho8AzaEAgNwENwQAE3KwAEnHgAoSQHMATnhQAHaDRRy5kAsEkBBJUoC0APgBip6IzyaAXNACSPPAGsYAdzAALToMgYleMBajACeANKQIZLmltaQJnSaACIAQjYA6nJgMABEjmAg-CAAXpCCOcjAvMAoSNAewN5cSijASNEWVpoAPCaUtPRMwDYAyuhYLAjQABQMZXUyvHWQuBjVkACUkv10BAzMJikrKHaQjQD6K6BrQQDiS5JHqH3Uu-vD0ABKlGSfsNuvQYHMydOJ2USwWAABRsAFYAAzw6AAemg5gATABmeHogCMdn60E03EgciCgg6sU0Jn0SjsACp6RDoXDEYy9AYTDEupA7J8znIQvUvD4-AEggRQhEoty4r1EpBUjZTFxhIzIAAPbCgAgyRnQPIEApFUrlSrVWrCxqcAgtNqUnm9Yw7IHDfmGVCYMDIXgYGAIAEDPZDQ7HU4XK4gG6Qe7tJ4oF5B958n5-QNvEMgqm8tGmLE4-HkahEyAksllB1xGkGBlMyEwhHw9laCmyBTKaBQhQBJAV2lc0G2BxOVxWpq+fyBYLhSKVnoJOJKzLZA35UAmsoVJBVGp1BpNW2tdqy+fOwHB5ijcbeqazSDzaCLZardZbF0X4Ch1DhzyXbdR9ZY0eY5EwzS8vlTf533eAds1rZkYQAFjZekUVzfM8QJYtiVJck50gJ0FSVJJICgIJVyNKoBGKLgZAqLRgEFaBeAIYR+HAEsumEdgJHw6s6WgRkEJsZCm3pDkjCzHk+QFIV91FScJSlWcTwIwwvxOQT6XsXxtDARh+GgNhwDwNxiFIRoYF4NA8BJZi6ks5AQm3Px6iWSwoBYspoA7NBIDYOJoFEksajkAh2VU-j4PrESUMkFtpEkIA)

**Comment by Chengxuan** [comment]
Greate diagrams @peterbroadhurst  🎉 

I like `the spelling of "Reject" being returning HTTP Status code 400`, may want to make the HTTP status code a list.


Below is my reasoning:

Regarding the logic to decide whether an error from a connector is retry-able, I see the following options:
- introduce a new mechanism that requires code changes in connectors to explicitly opt-in for all situations (delegate the decision-making to the connectors)
- introduce an implicit contract/assumption/convention in Firefly to do the decision-making itself and optionally connectors can update their code to embrace this convention

For the first option, one solution is introducing an HTTP response header for connectors to include when the error is non-retryable.


> the spelling of "Reject" being returning HTTP Status code 400 

This is an example implicit contract.

For this specific EVM connector error case, reserve 400 (one of the HTTP client error codes) as the implied contract does solve this specific issue (EVM reverted due to "bad" input param) nicely. 

I'm not so sure about other error cases.  As we are putting a constraint on which HTTP error code (400) can be returned for initialization failure, this forces connectors to use 400 for all the non-retryable errors that might be better represented using other HTTP error codes. (e.g. 409, 413).  Also, an error code like `413` can be a tricky one to override as it's often handled by HTTP middleware.

But it has a big advantage of less code change in the connectors and it can co-exist with solutions for the first option as well.

**Comment by awrichar** [comment]
I would lean toward the first proposal, where we move the operation to "failed" state if the gas estimation fails. As you said, this was the previous behavior, and I think it makes sense.

The second proposal, where we actually _delete_ the operation and all evidence of it, seems to be a pretty significant change to FireFly's behavior. I think it would be odd for the operation to exist for a few seconds and then not exist later.

On the choice of error codes... it seems like it should be HTTP 400 or 500. I think 400 makes sense if we can reasonably deduce that the request was invalid for some reason, which I do think is the general case being considered here.

**Comment by peterbroadhurst** [comment]
ok - thanks all.

I'm happy to stick with proposal 1:
- We spend the `idempotencyKey`
- Operation goes to `Failed` status

Given great input from @awrichar and @Chengxuan above, I propose returning `retryable: false` as an explicit JSON payload in the body of the error that flows back.

Note that the default will be `true` if `retryable` is omitted from the JSON, or is `null`.

> I did read the suggestion on a HTTP Header, but I believe currently got a contract being in the body of the response payload (for propagating error codes) and I think it makes sense to extend that with another parameter.

**Comment by peterbroadhurst** [comment]
The default-true semantics felt error-prone, so I have actually gone for `submissionRejected: true` as the API spelling in the FFTM layer.

**Comment by peterbroadhurst** [comment]
All of the changes, including the new E2E test in core, and releases of FFTM and EVMConnect, have been individually reviewed and are in mainline.
