### ISSUE TITLE
Expose server config

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly#15]
In Firefly Explorer, it would be useful to be able to fetch the config of my firefly node.

One use case I'm currently facing is determining the `default` namespace, this would be trivial if there was a way to access the config.

**Comment by nguyer** [comment]
@shorsher I realize fetching the config might be useful, but is the specific issue you're facing with the `default` namespace still a problem?

The new admin APIs could be enhanced to also show the full (file and DB merged) config. Exposing those on the regular API is probably too dangerous due to secrets being in config variables.
