### ISSUE TITLE
Add tags to /data endpoint

### ISSUE THREAD

**Issue by lil131** [hyperledger/firefly#198]
It would be great if `tag` could be added to `/data` endpoint, like the way it works on `/message`. It will be easier to categorize and retrieve data.

**Comment by panghalamit** [comment]
hd

**Comment by peterbroadhurst** [comment]
Hey @lil131,
The intended design is the `datatype.name` and `datatype.version` fields can be used for exactly this purpose.

If you specify `validator` as `json` then this `datatype` must have been broadcast to the network, with a JSON Schema that can be used to verify the data.

However, if you leave `validator` as blank, the data should not be verified at all - and you can simply use the `datatype` for classification of your data (without FireFly enforcing structure on it).

If you find a difference in behaviour from this, please say - as I know most of the testing / UTs so far have focussed on:
- JSON without a datatype set at all
- JSON with a verified datatype
- Binary blobs without a datatype set at all

... and I think you're looking for:
- Binary blobs with a datatype set

... or mabye:
- JSON with a datatype set, but without requiring FireFly to verify it

**Comment by lil131** [comment]
Thanks @peterbroadhurst! I'll try those on

**Comment by nguyer** [comment]
I tested this and it does not work currently

**Comment by peterbroadhurst** [comment]
Ok - looked into this some more.

Every `data` resource can have:
- An optional JSON `value`
- An optional `blob` reference
- _Or both_

https://github.com/hyperledger/firefly/blob/dcff6111530b683f7794bbf5e8ba0cc4d5652607/pkg/fftypes/data.go#L45-L46

The problem here is that the `verifier` defaults to `json`, and there is no way to specify `none`.
So if you specify a `datatype`, you are instructing the code to validate the `value` part of the data as JSON according to the schema, so the `datatype` must exist.

This prevents you from using the `datatype.name`/`datatype.value` fields for indexed categorization of the data, _without_ performing JSON schema verification.

Per this issue, that's a very valid requirement - so I plan to add `none` validator type, and also the tests for this scenario.
