### ISSUE TITLE
Create operation and transaction for custom smart contract calls

### ISSUE THREAD

**Issue by nguyer** [hyperledger/firefly#393]
Invoking a smart contract should be tracked by an `Operation` and a `Transaction` in FireFly.

**Comment by awrichar** [comment]
This item turns out to be difficult because we have no guarantees about what events may be emitted as a result of a custom smart contract call. This means many of the existing fields of `Transaction` can't be filled in, which means re-thinking the purpose of `Transaction` and how it fits into the landscape in light of all the custom onchain work.
