### ISSUE TITLE
Token transfer messages are delayed in batch assembly

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#421]
When a token transfer is sent with a message attachment, the message is first created in "staged" state, and then moved to "ready" once the transfer succeeds. On the sender node, this "ready" message is not immediately picked up for processing, but instead waits for the timeout that polls for new messages.

Seems like this could be because Orchestrator only listens for when messages are _created_, but this is actually a message being _updated_ (because it's just changing state to "ready") - so it isn't picked up.
https://github.com/hyperledger/firefly/blob/f56d701fa569de0a8b1597a2bfe17017b0260ecb/internal/orchestrator/persistence_events.go#L38

**Comment by peterbroadhurst** [comment]
Agree description above is spot on. Investigating a solution.

**Comment by peterbroadhurst** [comment]
Thought I was really close with this one, having worked out the shoulder-tap mechanism - then realized a complex aspect to the problem - and actually I'm not sure we would ever send the message in some circumstances.

We keep track of which messages we've assembled into batches, by simply moving a sequence offset forwards.
Unlike with pins we don't update the messages as they're assembed into a batch - rather we update them as the batch seals.

In this case, something is potentially dropping in _behind_ the most recent assembled batch, but if we rewind we might re-read ones we've put into the batch. So I need to think about this a bit more.

**Comment by peterbroadhurst** [comment]
At the moment this is how the batching logic works:
![batch_logic](https://user-images.githubusercontent.com/6660217/150621650-4c3ca62a-91e6-40b0-a73a-d6161e96ca39.jpg)

**Comment by peterbroadhurst** [comment]
This is my current thought of the new batch logic:

![new_batch_logic](https://user-images.githubusercontent.com/6660217/150622173-f2880f99-2226-475a-bc31-aa821fdcdc05.jpg)

- We remove one of the loops
- Persistence only happens once for each batch in the final stage when the batch is sealed
- Dispatching is async to the assembler
- The assembler only allows one batch to be in assembly before it blocks waiting for the dispatch completion
- The batch manager keeps track of all offsets dispatched to each active batch processor
- When dispatch is completed for an offset, that state is passed all the way back to the processor
- The manager updates the *persisted* offset, when the lowest offset dispatched to all processors is complete
- The manager keeps an in-memory offset to use for each DB polling cycle, which might be ahead of the persisted one
- The manager can rewind at any time, because everything will either:
  - Be persisted with a batch ID so skipped
  - Be already in-flight

**Comment by peterbroadhurst** [comment]
I've parked the rewind-on-db-update changes on this branch:
https://github.com/kaleido-io/firefly/tree/fix-421

Will hope to come back to this overall issue later today.

**Comment by peterbroadhurst** [comment]
Ok - been thinking a bit more about this.
Now everything said above is true, and I believe the architectural change above is worthwhile on the V1.0 timeframe (for efficiency, and restart resliience).

However, I'm also concerned as I think about it, that we've done something wonky by allowing the change in state of a message to cause it to be picked up _out of order_.

In this case there's no determinism in the order of that message. It might get picked up in any order into a batch, and on restart/recovery it's possible for that order to be different. This feels wrong to me.

So I think the immediate fix for this issue (which would be safer to backport to v0.11.x) is for when the message transitions into "ready" it gets assigned a new sequence that is further forwards in the stream. As if it were a new message.

This means a delete+recreate in a SQL world, but there should be similar constructs in all other databases to allow the most recent sequence to be allocated to the message.

**Comment by awrichar** [comment]
> So I think the immediate fix for this issue (which would be safer to backport to v0.11.x) is for when the message transitions into "ready" it gets assigned a new sequence that is further forwards in the stream. As if it were a new message.

This is absolutely correct. A "staged" message is not relevant at all for sequencing; it's just been stuffed away for (possible) future use. The "ready" state is the significant one that indicates a message is ready to get in the queue.
