### ISSUE TITLE
FF-Perf: Request failed with status code 429 in tokens connector

### ISSUE THREAD

**Issue by eberger727** [hyperledger/firefly#541]
When running a performance test of 300 token mints, when the go routines first start sending API requests, the Nest.js token connector gets overwhelmed and returns `429: Too Many Requests` for all but 65 requests; hinting that the connector is rate limiting requests. Maybe there's a way to increase the limit?

[tokens-connector.log](https://github.com/hyperledger/firefly/files/8118010/tokens-connector.log)
[ff-perf.log](https://github.com/hyperledger/firefly/files/8118031/ff-perf.log)
[log_ethconnect_0.log](https://github.com/hyperledger/firefly/files/8118032/log_ethconnect_0.log)
[log_firefly_core_0.log.zip](https://github.com/hyperledger/firefly/files/8118033/log_firefly_core_0.log.zip)

**Comment by awrichar** [comment]
This is probably ethconnect rejecting the requests. Because we're using the direct webhook plugin of ethconnect and not a more robust message queue, it has a finite configurable limit of transactions in flight. See https://github.com/hyperledger/firefly-ethconnect/issues/185

Assuming we don't want to use a "better" message queue in ethconnect for this test, this is probably a matter of tuning `MaxInFlight` on ethconnect to be a bit higher.

**Comment by peterbroadhurst** [comment]
So I don't think this one is necessarily to fix in FireFly core. In core there is retry configurable to handle 429s, if you have a hosted copy of ethconnect running in a cloud environment with rate limiting, where that limit is too low (likely the case here). 

Having configurable retry in tokens connectors would be a good thing to raise against those individually, if retry is not configurable there.
