### ISSUE TITLE
Enhancements to event data & websocket event filtering

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly#545]
Events are extremely important to FireFly applications, but purposefully don't contain a large amount of information. After speaking with @eberger727 and @awrichar it was decided adding a new field, `ReferenceType`, would be useful to help developers determine which tables the events `ref` refers. 

<img width="853" alt="Screen Shot 2022-02-22 at 4 48 19 PM" src="https://user-images.githubusercontent.com/10987380/155225250-3ee40868-f6ac-4529-b938-35b43c4698da.png">

The above events break down into the following categories, which will be the possible values of `ReferenceType`

* TokenTransfer
* TransferOperation
* Messages
* BlockchainEvent
* TransactionSubmitted
* TokenApproval [0]
* TokenApprovalOperations [0]

[0]: Coming in https://github.com/hyperledger/firefly/pull/529

**Comment by awrichar** [comment]
So I realized after discussing this, that the `Reference` values of the Definition types actually do _not_ refer to a Message. They refer to the created object (a Namespace, Datatype, Token Pool, etc). So there actually are nearly as many reference types as there are operations. The only common ones are that `message_confirmed` and `message_rejected` both refer to a Message, and `token_transfer_op_failed` and `token_approval_op_failed` both refer to an Operation. Probably not enough commonality to warrant the `ReferenceType` now that I've thought on it further.

I think it may be more beneficial to introduce a `Category` in order to group the events by the 4 colors in the graphic above.

**Comment by awrichar** [comment]
I know we also talked about enhancing the `enrichEvents` method here:
https://github.com/hyperledger/firefly/blob/d03b868663d460f5eba503ee4652f2fced0e6d01/internal/events/event_dispatcher.go#L161

But as I mentioned above, there are actually a _lot_ of different tables to which the `Reference` field might point. Need to decide if we want a 12-way `switch` on `Type` to always fetch the referenced object, or if we pick and choose only certain events to "enrich".

**Comment by awrichar** [comment]
Another angle to dump in here - when creating a websocket subscription, you're able to filter events by a lot of message-specific things, like `author`, `tag`, `topics`. These filters won't be relevant for non-message event types. At the same time, we may want other filters for non-message things, such as filtering `blockchain_event` events to only certain event names.

We don't have to solve all of this at once, but there's a lot of subtlety to the picture since events can reference so many different types of things.

**Comment by shorsher** [comment]
> Also wondering whether we need to even store this in the database, or if it should be derived and just annotated on the event by a switch case after loading...

I'm good with only annotation

**Comment by awrichar** [comment]
Yea after even further thought/discussion, seems like `category` is not really necessary all the way down in the database - and maybe not even in the API layer at all. The primary driver behind wanting it was to do color-coding on the UI, but if we have a way to aggregate events by type, then the categorization can be done relatively easily all the way up at the UI level. Feels like we've come full circle on this, but probably no changes to the database table needed here.

I think we _do_ definitely need to extend `enrichEvents` and `filterEvents` to support processing events that reference something other than Messages. At the very least we should pull in details from Transactions (for `transaction_submitted`) and Blockchain Events (for `blockchain_event`).

**Comment by shorsher** [comment]
Going to jot down the work items here:

* Define the current web socket events behavior (thanks @nguyer 😄) and ensure blockchain events are included by default
* Outline the applicable filters for each event type
* Extend `filterEvents` to support additional filtering based on `type`.
  * i.e. filter on `type=blockchain_event` and `blockchain_event.name=<value>`, where the latter is currently missing
* Enhance `enrichEvents` to provide additional information for `blockchain_events` and `transactions`
* Add the ability for the enriched information to be included in API responses via an optional flag

**Comment by awrichar** [comment]
Might want to change the title/summary of this issue since we just made it into a totally different thing 😄

**Comment by awrichar** [comment]
> if we have a way to aggregate events by type

btw is this bit being handled elsewhere by @eberger727? I think it's not in scope above.

**Comment by shorsher** [comment]
Here's my first attempt at mapping the event types to the FF construct you can filter on:

<img width="375" alt="Screen Shot 2022-02-23 at 4 27 53 PM" src="https://user-images.githubusercontent.com/10987380/155411525-e2419049-516d-46f2-ac05-ba9e5bb126b2.png">

**Comment by shorsher** [comment]
For the time being, we're only going to add filters for `Messages`, `Transactions`, and `BlockchainEvents`.
