### ISSUE TITLE
Operations: Add operation for Shared Storage (IPFS) uploads, and move API calls to batch worker

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#568]

**Comment by awrichar** [comment]
Took an initial look at this, and found one blocker. Currently we write the public IPFS reference as part of the batch payload, which is hashed and stored by the batch processor _before_ being passed to the broadcast manager for dispatch. This means that the IPFS upload must happen prior to all of this in order to compute a valid batch hash, which implies it cannot happen during the dispatch step.

There are roughly two routes forward (although there may be many details on how to achieve either one):
1. Break the batch processing into more stages, such that the IPFS upload can happen during batch processing but prior to hashing and storing the batch
2. Perform the IPFS upload when dispatching the batch, but adjust the batch payload so that the IPFS reference does not invalidate the hash when it is added

I'd lean slightly toward the latter, although this probably needs some discussion and may tie into the batch payload changes in #506.

**Comment by awrichar** [comment]
Part of this work is now accomplished in #596
