### ISSUE TITLE
Documentation: Run through the Tutorials docs end-to-end and capture many improvement suggestions

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly#573]

**Comment by trevorsc19** [comment]
Universal comment - Tutorials were written for people to interact with firefly through the CLI/Postman.  Now that we have the Sandbox UI we should probably go through and redo a number of these instructions to point people towards the UI since that seems like a simpler user experience.

**Broadcast Data**

- Key Concepts link is broken (404)
- Example 3: would be good to add explicit information on how users can download that file through the sandbox. Maybe we could move that download button from the right hand side in the unmarked column to show up as an option when you click on the blob name (where a popup already shows up to copy the name of the blob)

**Privately Send Data**

- Key Concepts link is broken (404)
- I see this comment in both the Broadcast and Privately send data section: "Issue [[#112](https://github.com/hyperledger/firefly/issues/112)](https://github.com/hyperledger/firefly/issues/112) proposes adding an option to wait for the message to be confirmed by the blockchain before returning, with 200 OK." but when I use the UI I send a transaction and immediately get a 202 response. Has the result of this issue been implemented on the UI or should this note be removed/modified?

**Explore Messages**

- This section needs to be redone to account for the new UI.

**Listen for Events**

- Key Concepts link is broken (404)

**Define a datatype**

- Key Concepts link is broken (404)

**Mint some tokens**

- Not an issue with the documentation, but the UI doesn't have the ability to send a message with transaction. I see that the message field is empty when we look at the transfer in the UI, but there's no ability to send message

**Working with custom smart contracts**

- contract deployment section - Let's link them to either the FAQ or the page that Nicko makes about deploying contracts.
