### ISSUE TITLE
Token pool definitions are all broadcast on a single topic

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly#597]
Within a namespace, all token pool definition messages are broadcast on one topic. They could be split onto unique topics to enhance throughput, as long as the topic gives a deterministic "winner" for creating the pool in the case of a race (ie the topic should probably be some function of namespace+name).

**Comment by peterbroadhurst** [comment]
For identities we use the `did` because that:
- Includes the name
- Includes something unique to identities (`did:`)

https://github.com/hyperledger/firefly/blob/491c2723f51887ff4fb402ffc72c5e9c6f83fa3a/pkg/fftypes/identity.go#L152-L156

I think for token pools, we'd need to hash:
- A string such as `tokenpool`
- The name

**Comment by awrichar** [comment]
Fixed in https://github.com/hyperledger/firefly/pull/600
